apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: {name: api, namespace: shop}
spec:
  replicas: 5
  selector: {matchLabels: {app: api}}
  template:
    metadata: {labels: {app: api}}
    spec:
      containers:
        - name: api
          image: lab-api:v2
          ports: [{containerPort: 8000, name: http}]
  strategy:
    canary:
      analysis:
        templates: [{templateName: error-rate}]
        startingStep: 1
      steps:
        - setWeight: 10
        - pause: {duration: 2m}
        - setWeight: 50
        - pause: {duration: 2m}
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata: {name: error-rate, namespace: shop}
spec:
  metrics:
    - name: error-rate
      interval: 30s
      failureLimit: 2
      successCondition: result[0] < 0.05
      provider:
        prometheus:
          address: http://mon-kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(http_requests_total{job="api",status=~"5.."}[1m]))
            / sum(rate(http_requests_total{job="api"}[1m]))
